### ISSUE TITLE
Ignore some channels like #karhu and private messages

### ISSUE THREAD

**Issue by kymppi** [Testausserveri/testauskoira-rs#14]
Because now someone can spam in them and get the role. This time it is the correct repo for the issue.

**Comment by kymppi** [comment]
Wdym by wontfix label 
![contabo](https://user-images.githubusercontent.com/48528700/148270583-c21c8e98-9e74-4bdb-a11a-c39e0021c3f0.png)

**Comment by Esinko** [comment]
This needs to be fixed asap!

**Comment by DrVilepis** [comment]
Implemented a temporary fix, this will be handled in testausapis in the future
