### ISSUE TITLE
Translate "most active members" embed to Finnish

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testauskoira-rs#38]
Everything else on the server is in Finnish so let's stick with that ;)

<img width="393" alt="image" src="https://user-images.githubusercontent.com/46541386/151451338-c7db64cb-5b34-43fb-b082-05920713ae0a.png">

**Comment by ahnl** [comment]
Also good job on the profile picture graphic masking, looking good.

![image](https://user-images.githubusercontent.com/46541386/151451680-a62c09b9-2be3-4413-8ddd-95ebde81cfdb.png)

**Comment by ihmemaassa** [comment]
I'll try this one

**Comment by lajp** [comment]
Closed in #39
