### ISSUE TITLE
Self-service roles

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testauskoira-rs#65]
Create a slash command to add roles to oneself. The idea is to let people add custom roles to itself, such as @csgo @karhu or other roles.

- /rooli (no params)
- Returns an interaction response with multiselect dropdown to choose roles

**Comment by lajp** [comment]
Should it be `/role`rather than `/rooli` because all the other commands are also English

**Comment by Chicken** [comment]
The finglish is so strong in the whole project so does it even matter anymore

**Comment by bluelhf** [comment]
Perhaps it'd be good to use the French `rôle` for variety?

**Comment by Chicken** [comment]
If we want to go for variety I'd suggest using Swedish, after all it's our second official language.

**Comment by lajp** [comment]
So then it would be `/roll

**Comment by bluelhf** [comment]
> If we want to go for variety I'd suggest using Swedish, after all it's our second official language.

I thought of this, but I thought it might cause confusion, as users may expect Testauskoira to be able to roll, and possibly even to do more tricks, like sit, or give paw.

**Comment by Chicken** [comment]
That could be another feature request, to play with testauskoira.
