### ISSUE TITLE
Use timeout

### ISSUE THREAD

**Issue by Chicken** [Testausserveri/testauskoira-rs#69]
Use the Discord provided timeout moderation for silencing offenders instead of a role. The current role system is vulnerable to permission misconfiguration.

**Comment by DrVilepis** [comment]
I am unsure of the state of support for this feature in the library we are using. We will implement this if we are capable.

**Comment by Mixu78** [comment]
Serenity has full support for timeouts

**Comment by DrVilepis** [comment]
In that case consider this done.

**Comment by lajp** [comment]
How should I implement this? Should the timeout be similar to how the role works, making it's duration infinite?

**Comment by Chicken** [comment]
If that's possible, yes.

**Comment by lajp** [comment]
It'd be somewhat abusing the feature but I think It'll be possible. Although the maximum duration of a timeout is 1 week, which seems a long time and probably more than enough to outlast a trolls patience.

**Comment by Chicken** [comment]
Week is enough, they will be probably banned after mods wakeup anyway.

**Comment by lajp** [comment]
Closed by https://github.com/Testausserveri/testauskoira-rs/commit/0451c6f511d5cdfd57afe8070b3b7760bb87aaf1
