### ISSUE TITLE
Remove notification to offenders

### ISSUE THREAD

**Issue by Chicken** [Testausserveri/testauskoira-rs#70]
Remove the direct message sent to users about being reported. This is an easily abusable feature to send unsolicited direct messages to users. There's also absolutely no need for this as only the council needs to know the reported messages. In fact this only benefits the trolls because it serves as a warning to do as much damage as possible before being silenced.

**Comment by DrVilepis** [comment]
Seems reasonable, I will fix this.

**Comment by lajp** [comment]
I think there has been already some discussion about this. It'll be an easy fix but I'd like to first have some kind of vote on it.

**Comment by Chicken** [comment]
Unnecessary bureaucracy, don't think anybody ever asked for it to be a thing. It's just been there since the implementation.

**Comment by lajp** [comment]
Well the reason why it's there is that non-trolls have some time to re-evaluate their message and potentially delete it before the council has to take any punitive actions.

**Comment by lajp** [comment]
In that case 1 week or 1 day?

**Comment by bluelhf** [comment]
The report feature seems to be rarely used in such cases, and is mostly used for trolls. If a more trusted member says something inappropriate, it's more likely that people will express their concerns verbally, so in my opinion removing the notification is fine.

**Comment by lajp** [comment]
Thank you for your input. Based on this conversation and a vote over on discord I'm going to remove the message shortly.
