### ISSUE TITLE
Don't hard-code the rules channel id

### ISSUE THREAD

**Issue by Eldemarkki** [Testausserveri/testauskoira-rs#73]
The channel id at the end of this line should probably be specified in the .env file: 
https://github.com/Testausserveri/testauskoira-rs/blob/7f5d37c484b4771ddc345f65736159d3c71234d8/src/voting.rs#L461

**Comment by lajp** [comment]
Yes. Thank you for the insight. Are you willing to attempt the implementation yourself or do you want me to take care of this.

**Comment by Eldemarkki** [comment]
I can probably do it, but not right now. Probably in the evening or maybe tomorrow.

**Comment by lajp** [comment]
That is all right. Looking forward to the PR. :)

**Comment by Eldemarkki** [comment]
I'm having a bit of trouble getting the application commands working (I can't see the report-button when right clicking a message, even though the Discord API says the command has been registered). I tried debugging it for a few hours but couldn't fix it. Could you do this, because I don't think I would be able to figure that problem out in a reasonable amount of time? It shouldn't take too long (_famous last words_), but for me the problem is just getting the dev environment running.

**Comment by lajp** [comment]
Hmm, this is odd. I think there is no hurry in implementing this so if you feel like it you can take your time in getting your dev-environment up. Also it is likely that the main reason for these difficulties is poor documentation from our side, so feel free to reach over and we'll to help you to get your setup going
