### ISSUE TITLE
Vote feature

### ISSUE THREAD

**Issue by developerfromjokela** [Testausserveri/testauskoira-rs#74]
Testauskoira could be even more useful, if it had a voting feature.

A vote should be initiated with a command by admins, and a message/embed should appear on channel defined in settings.

By adding reactions, people should be able to vote.

**Comment by DrVilepis** [comment]
Debatably this could be startable by anyone in any channel, so anyone can do a vote if they want to, only admins have access to announcement channels so you can simply type the command there to get a vote if you need to.

**Comment by ahnl** [comment]
There used to be another idea related to voting. 

It was to create an idea channel, where people can submit their feature ideas for improving our community. A bot would start a thread from the message and add thumbs up/down reactions to it. This would allow members to discuss a feature idea, and vote for its neccessity.

I would love to see this feature as Masterminds could clearly see what is important to improve, without great ideas disappearing into sea of messages.

**Comment by lajp** [comment]
> It was to create an idea channel, where people can submit their feature ideas for improving our community.
I imagine this channel would be violently rate-limited then. (slowmode)

And I agree here with @DrVilepis if I were to implement a voting feature it'd bee cool for me to be able to use it myself. Unlike giveaways votes, in my opinion, are something anyone should be able to start.

**Comment by developerfromjokela** [comment]
I think the scope of who can start a vote should be limited to i.e. only arvojäsenet and above. That would avoid unnecessary and somewhat spam votes being created

**Comment by developerfromjokela** [comment]
One idea would be, that voting is limited to channel it was started. i.e. starting a vote in general, would start voting process there.

**Comment by ahnl** [comment]
Let's keep in mind that arvojäsenet is no more role for active members, but rather for trusted members. It is not clear how to earn it, to finally enjoy the benefits such as managing the event calendar and [creating votings]. So, alternatively we could allow everyone to create votings, and limit the access later if problems arise.

I could also suggest that votings wouldn't be big chunky embeds, but something smaller. It could look less spammy in chats that way.

Limiting access to arvojäsenet only, is OK for me. Feel free to have further discussions about the above if someone doesn't like the arvojäsenet only access.



> > It was to create an idea channel, where people can submit their feature ideas for improving our community.
> 
> I imagine this channel would be violently rate-limited then. (slowmode)

Yep, it would make sense to rate-limit the channel.

**Comment by developerfromjokela** [comment]
> Let's keep in mind that arvojäsenet is no more role for active members, but rather for trusted members. It is not clear how to earn it, to finally enjoy the benefits such as managing the event calendar and [creating votings]. So, alternatively we could allow everyone to create votings, and limit the access later if problems arise.
> 
> I could also suggest that votings wouldn't be big chunky embeds, but something smaller. It could look less spammy in chats that way.
> 
> Limiting access to arvojäsenet only, is OK for me. Feel free to have further discussions about the above if someone doesn't like the arvojäsenet only access.
> 
> > > It was to create an idea channel, where people can submit their feature ideas for improving our community.
> > 
> > 
> > I imagine this channel would be violently rate-limited then. (slowmode)
> 
> Yep, it would make sense to rate-limit the channel.

I agree. Let's do rate-limiting, and if further abuses happen, restricting is always an option.
