### ISSUE TITLE
Giveaway feature

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testauskoira-rs#9]
We use [SoCuul/GivneawayBot](https://github.com/SoCuul/GiveawayBot) for running giveaways. Should we move away from 3rd party non-maintained giveaway bot and include the feature in Testauskoira?

<img width="695" alt="image" src="https://user-images.githubusercontent.com/46541386/147855693-f0dceaf1-37fc-487a-8319-41acc3856b39.png">

**Comment by Esinko** [comment]
@DrVilepis @lajp This should be your next priority in development, after all other base-level features are functional.

**Comment by DrVilepis** [comment]
Noted

**Comment by lajp** [comment]
Yeah, I've already started the implementation to some degree.. Also I think @Mixu78 is/was working on this.

**Comment by lajp** [comment]
This is now implemeted by #29 
Thank you @Mixu78 for your amazing work on this!
